%YAML 1.2
---
gpu: 0

dataset:
  input_train: '/home/gridsan/pnegi/maia-chess/1100traindata/training/*/*'
  input_test: '/home/gridsan/pnegi/maia-chess/1100traindata/validation/*/*'
common:
  train_cycles: 100 #1 cycle = disc + gen run for total_steps_per_cyckle
  batch_size: 1024
  num_batch_splits: 1
  shuffle_size: 250000

gen_training:
  precision: 'single'
  test_steps: 50
  train_avg_report_steps: 50
  total_steps_per_cycle: 10000
  checkpoint_steps: 10000
  lr_values:
      - 0.01
      - 0.001
      - 0.0001
  lr_boundaries:
      - 50000
      - 500000
  policy_loss_weight: 1.0            # weight of policy loss
  value_loss_weight:  0.0            # weight of value loss
  #loss_func: 'ce'
  loss_func: 'discriminator'

gen_model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8

disc_training:
  precision: 'single'
  test_steps: 50
  train_avg_report_steps: 50

  total_steps_per_cycle: 100
  checkpoint_steps: 10000
  lr_values:
      - 0.01
      - 0.001
      - 0.0001
  lr_boundaries:
      - 6000
      - 10000
  policy_loss_weight: 1.0            # weight of policy loss
  value_loss_weight:  0.0            # weight of value loss
disc_model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
  final_flat_blocks: 2
  final_flat_hls: 2048
...
